const quotes = [
 "Don't let the fear of losing be greater than the excitement of winning (Robert Kiyosaki)",
 "The way to get started is to quit talking and begin doing (Walt Disney)",
 "The successful warrior is the average man with a laser like focus (Bruce Lee)",
 "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful (Albert Schweitzer)",
 "Fall seven times and stand up eight (Japanese proverb)",
 "If you can dream it, you can do it (Walt Disney)",
 "In order to succeed, we must first believe we can (Nikos Kazantzakis)",
 "Don't be distracted by criticism. Remember the only taste of success some people get is to take a bite out of you (Zig Ziglar)",
 "Keep on going, and the chances are that you will stumble on something, perhaps when you are least expecting it. I never heard of anyone ever stumbling on something sitting down (Charles F. Kettering)",
 "There are two types of people, those that will tell you that you cannot make a difference in the world, and those who are afraid you will succeed (Ray Goforth)",
 "Successful people do what unsuccessful people are not willing to do. Don't wish it was easier, wish you were better (Jim Rohn)",
 "Never give in except to convictions of honor and good sense (Winston Churchill)",
 "Stop chasing the money and start chasing the passion (Tony Hsieh)",
 "Success is walking from failure to failure without the loss of enthusiasm (Winston Churchill)",
 "If you are not willing to risk the usual, you will have to settle for the ordinary (Jim Rohn)",
 "The ones that are crazy enough to think they can change the world, are the ones that do (Anonymous)",
 "Do one thing everyday that scares you (Anonymous)",
 "All progress takes place outside the comfort zone (John Bobak)",
 "Be yourself, everyone else is already taken (Oscar Wilde)",
 "Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind (Dr Seuss)",
 "How people treat you is their karma, how you react is yours (Wayne Dyer)",
 "Courage is the quality of every quality at its highest testing point (Anonymous)",
 "He who rules his own spirit is better than the one who taketh a city (Anonymous)",
 "We are not human beings having a spiritual experience; we are spiritual beings having a human experience (Teilhard de Chardin)",
 "Me lift thee and thee lift me, and will both ascend together (John Greenleaf Whittler)",
 "The water that is still and deep has the devil resting at the bottom (Anonymous)",
 "Knowledge is knowing what to say. Wisdom is knowing whether or not to say it (Anonymous)",
 "Not all storms come to disrupt your life, some come to clear your path (Anonymous)",
 "Be real. Not perfect (Anonymous)",
 "Your boring life is someone's else dream (Anonymous)",
 "Keep your big dreams/ideas away from small minds (Anonymous)",
 "A smooth sea never made a skilled sailor (Anonymous)",
 "One day, every failure will make sense (Anonymous)",
 "You don't have what you want because you deserve much better (Anonymous)",
 "If you don't have confidence in self, you are twice defeated in the race of life (Marcus Garvey)",
 "The pen is mightier than the sword, but the tongue is mightier than them both put together (Marcus Garvey)",
 "The deepest hunger of the human body is air. The deepest hunger of the human heart is to feel understood, valued, and respected (Anonymous)",
 "If you do what you have always done, you will get what you have always gotten (Anonymous)",
 "Simplicity is prerequisite for reliability (Edsger W. Dijkstra)",
 "Today is a gift, that is why it is called the Present (Anonymous)",
 "In authenticity we trust - Get real or get lost (Anonymous)",
 "Nobody watches you harder than the people that don't like you. Give them a show (Anonymous)",
 "Seek out the people and places that resonates with your soul (Anonymous)",
 "Just because you can doesn't mean you should (Anonymous)",
 "Happiness is not a permanent state. Wholeness is. Don't confuse the two (Anonymous)",
 "Ask for what you want. The worst thing they can say is no (Anonymous)",
 "Fall hard and forever in love with yourself (Anonymous)",
 "Question everything except your own intuition (Anonymous)",
 "No matter where you are, you can always come home (Anonymous)",
 "Be okay with being misunderstood. You are not here to convince other people to see you differently (Anonymous)",
 "If you have a chance to make people happy, just do it. Sometimes people are struggling silently (Anonymous)",
 "Love what you have before life teaches you to love what you lost (Anonymous)",
 "Sometimes your heart needs more time to accept what your mind already knows (Anonymous)",
 "Most people go to their graves with their music still in them (Benjamin Disraeli)",
 "Life is what happens while you are making plans (John Lennon)",
 "It is not the strongest or the most intelligent that will survive but those that can manage change (Steve Magness)",
 "Anything you can do needs to be done, so pick up the tool of your choice and get started (Bon Linder)",
 "You are the expert on what you need, so listen to yourself (Anonymous)",
 "A foolish consistency is the hobgoblin of little minds (Ralph Waldo Emerson)",
 "Creative ideas can't be forced, they have a life on their own (Anonymous)",
 "The wise person listens to everyone and thanks them for their opinion. Then he sends them away and does what he thinks best (Anonymous)",
 "Waiting until you get it just right is not a good idea (Anonymous)",
 "Let yourself be silently drawn by the strange pull of what you really love. It will not lead you astray (Rumi)",
 "Rejection is another person's opinion of you, you can choose to accept it as a fact or not (Anonymous)",
 "Some people are late bloomers (Anonymous)",
 "As long as you stay in the race, the hope of eventual victory is kept alive (Anonymous)",
 "As soon as you trust yourself, you will know how to live (Goethe)",
 "Never build a case against yourself (Robert Rowbottom)",
 "No one can make you feel inferior without your consent (Eleanar Roosevelt)",
 "Everything has an end (A Masaai's saying)",
 "Self-trust is the first secret of success (Ralph Waldo Emerson)",
 "Ther came a time when the risk to reamin tight in the bud was more painfull than the risk it took to blossom (Anais Nin)",
"Change is good. Focused change is better. Directed change is the best of all (Anonymous)",
"I have been in the sorrow's kitchen and licked all the pots. Then I have stood on the peaky mountain wrapped in rainbows, with a harp and sword in my hand (Zora Neale Hurston)",
"A great many people think they are thinking when they are merely rearranging their prejudices (William James)",
"We find comfort among those who agree with us, growth among those who don't (Frank Clarke)",
"Men stumble over the truth from time to time, but most pick themselves up and hurry off as if nothing happened (Winston Churchill)",
"The gem cannot be polished without friction nor a man without trials (Chinese proverb)",
"He that wrestles with us strengthen our nerves, and sharpen our skills. Our antagonist is our helper (Burke)",
"Wise people seek solutions, the ignorant cast blame (Lao Tzu)",
"The essence of genius is to know what to overlook (William James)",
"Well timed silence has more eloquence than speech (Martin Tupper)",
"To be nobody but yourself - in a world which is doing its best, day and night, to make you everybody else - means to fight the hardest battle which any human being can fight, and never stop fighting",
"Life can be pulled by goals just as surely as it can be pushed by drives (Viktor Frankl)",
"The cruelest lies are often told in silence (Virginibus Puerisque)",
"Don't ask youself what the world needs. Ask yourself what makes you come alive and then go and do that. Because what the world needs is people who have come alive (Howard Thurman)",
"Self esteem is a quiet and relatively unshakable sense of satisfaction that comes from recognizing and appreciating our existing worth, and then choosing to love and grow (Glen R. Schiraldi)",
"There will always be someone who can't see your worth. Don't let it be you (Dita Von Teese)",
"Confidence in yourself is built through acts of everyday courage (Anonymous)",
"If it doesn't open, it's not your door (Anonymous)",
"Some days you need the music and some days you need the lyrics (Anonymous)",
"Making mistakes is better than faking perfections (Anonymous)",
"It is better to lose someone instead of losing your mind (Anonymous)",
"It is common sense to take a method and try it, if it fails, admit it frankly and try another. But above all, try something (Franklin D. Roosevelt)",
"Do not pray for tasks equal to your powers. Pray for powers equal to your tasks (Phillips Brooks)",
"The only thing we have to fear is fear itself (Franklin D. Roosevelt)",
"It is hard to enlarge your horizons when you are busy defending your borders (Anonymous)",
"The dream is the royal road to the unconcious (Sigmund Freud)",
"Do everything and expect nothing (Anonymous)",
"Mothers don't fear death. Their greatest fear is leaving their children in this world, knowing no one will love them like they do (Anonymous)",
"People who are unable to motivate themselves must be content with mediocrity, no matter how impressive their other talents (Andrew Carnegie)"
];

export default quotes;